export const SESSION = "SESSION";
export const BREAK = "BREAK";
export const CHANGE_MODE = "CHANGE_MODE";
export const SET_CONFIGURATION = "SET_CONFIGURATION";
export const START_TIMER = "START_TIMER";
export const STOP_TIMER = "STOP_TIMER";
export const UPDATE_TIMER = "UPDATE_TIMER";
export const RESET_TIMER = "RESET_TIMER";

export const ADD_QUOTES_STARTED = "ADD_QUOTES_STARTED";
export const ADD_QUOTES_SUCCESS = "ADD_QUOTES_SUCCESS";
export const ADD_QUOTES_FAILURE = "ADD_QUOTES_FAILURE";
